DELETE FROM USUARIO_PERFIL WHERE USUARIO_ID IN ('emgonzalez','emnava');
DELETE FROM USUARIO        WHERE USUARIO_ID IN ('emgonzalez','emnava');

INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('emnava',1,'ESTEFANY MONSERRATH NAVA ESCOBAR','716f4e63b76d6284917d37a8d8219cf5','emnava@perfumeriamarlen.com.mx',1); 
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('emgonzalez',1,'EDITH MAGALLY GONZALEZ HERNANDEZ','d3b7974ec34fece9d27a7373812a5f75','emgonzalez@perfumeriamarlen.com.mx',1);

INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('emgonzalez','pmarlenuser');
INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('emgonzalez','stock');
INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('emnava','finances');
INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('emnava','pmarlenuser');
INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('emnava','stock');

INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('aestrada',1,'ALFREDO ESTRADA GONZÁLEZ','18f57349baa42ac813ce3b55dc25d7a4','aestrada@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('aleon',1,'ANA LEON','18f57349baa42ac813ce3b55dc25d7a4','aleon@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('dleon',1,'DANIEL LEON','fa22bd28df5d3dcf6768c2dc0d18101c','dleon@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('hmiranda',0,'HILDA MIRANDA','18f57349baa42ac813ce3b55dc25d7a4','dleon@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('jnieto',0,'JANETH NIETO','18f57349baa42ac813ce3b55dc25d7a4','jnieto@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('dolvera',0,'DAVID OLVERA','18f57349baa42ac813ce3b55dc25d7a4','dolvera@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('mcruz',0,'Maria Cruz Monter Maldonado','18f57349baa42ac813ce3b55dc25d7a4','mcruz@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('msabino',0,'MAGALI SABINO MONROY','542f0576b17a3a74df6903123102843e','msabino@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('rkcuevaz',0,'ROSA KARINA CUEVAS CORTEZ','ceaccbe3e7e0910a607bc63074440d62','rkcuevaz@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('mgonzalez',0,'MIRIAM GONZÁLEZ PAULÍN','4873c21b9e57a0276108acf734b4b7e8','mgonzalez@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('rlopez',0,'RENE LOPEZ','669a460b3cf8b270ba8d335bf30360b7','rlopez@perfumeriamarlen.com.mx',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('caja3',0,'CAJA 3','996e4a44a47c38501495130014b32a80','nomail@mail.com',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('caja4',0,'CAJA 4','465631ed7b9e365e35cd2e3fa75ccb56','nomail@mail.com',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('caja5',0,'CAJA 5','8585e3394a4b5b02a515b970f66b839a','nomail@mail.com',1);
INSERT INTO USUARIO(USUARIO_ID ,HABILITADO ,NOMBRE_COMPLETO,PASSWORD,EMAIL,SUCURSAL_ID) VALUES ('caja6',0,'CAJA 6','3da618a2332903fad3af87590f5489de','nomail@mail.com',1);

INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('aestrada','finances');
INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('aestrada','pmarlenuser');
INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('aestrada','stock');

INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('aleon','pmarlenuser');
INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('aleon','stock');

INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('dleon','pmarlenuser');
INSERT INTO USUARIO_PERFIL(USUARIO_ID,PERFIL_ID) VALUES('dleon','stock');

